package com.rolling_stones.rollingstonesandroid.application;


public interface Constants {

    String KEY_SELECTED_USER_ID = "KEY_SELECTED_USER_ID";
    String KEY_SELECTED_GROUP_ID = "KEY_SELECTED_GROUP_IDS";
    String KEY_CURRENT_POSITION = "KEY_CURRENT_POSITION";

    String TAG_DIALOG_DATE_PICKER = "TAG_DIALOG_DATE_PICKER";
    String TAG_DIALOG_CHANGE_PASSWORD = "TAG_DIALOG_CHANGE_PASSWORD";
    String TAG_DIALOG_SELECT_FRIENDS = "TAG_DIALOG_SELECT_FRIENDS";
    String TAG_DIALOG_FONT_STYLE = "TAG_DIALOG_FONT_STYLE";
    String TAG_DIALOG_LIST_ORDER = "TAG_DIALOG_LIST_ORDER";
    String TAG_DIALOG_LOGOUT = "TAG_DIALOG_LOGOUT";
    String TAG_DIALOG_DELETE_ACCOUNT = "TAG_DIALOG_DELETE_ACCOUNT";
    String TAG_DIALOG_WEB_API_SETTINGS = "TAG_DIALOG_WEB_API_SETTINGS";

    int REQUEST_IMAGE_CAPTURE = 101;
    int REQUEST_CODE_SPEECH_INPUT = 202;
}
